myshop/cart/urls.py
from django.urls import re_path 
from . import views


urlpatterns = [
    re_path(r'^$', views.cart_detail, name='cart_detail'),
    re_path(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    re_path(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

myshop/myshop/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import include
from django.urls import re_path 

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'about_us/', include(('about_us.urls', 'about_us'), namespace='about_us')),
    re_path(r'^orders/', include(('orders.urls', 'orders'), namespace='orders')),
    re_path(r'^cart/', include(('cart.urls', "cart"), namespace='cart')),
    re_path(r'^', include(('shop.urls', 'shop'), namespace='shop')), 
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myshop/orders/urls.py
from . import views
from django.urls import re_path 


urlpatterns = [
    re_path(r'^create/$', views.order_create, name='order_create'),
    re_path(r'^admin/order/(?P<order_id>\d+)/$', views.admin_order_detail, name='admin_order_detail'),
]

myshop/cart/models.py
from django.db import models

# Create your models here.

myshop/cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 3)]


class CartAddProductForm(forms.Form):
    quantity = 1
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

myshop/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=1,
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')

def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

def cart_detail(request):
    cart = Cart(request)
    return render(request, 'cart/detail.html', {'cart': cart})

myshop/templates/cart/detail.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
    Your shopping cart
{% endblock %}
{% block content %} 
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br> 
    <form action="{% url 'orders:order_create' %}">
        <center><button type="submit" class="btn-cart">Оформить заказ</button></center>
    </form>
    <div class="cart-container">
        <table class="cart">
            <thead>
                <tr>
                    <th class="titillium-web-black">Фото</th>
                    <th class="titillium-web-black">Товар</th>
                    <th class="titillium-web-black">Количество</th>
                    <th class="titillium-web-black">Убрать</th>
                    <th class="titillium-web-black">Цена за 1 шт.</th>
                    <th class="titillium-web-black">Итого</th>
                </tr>
            </thead>
            <tbody>
                {% for item in cart %}
                    {% with product=item.product %}
                        <tr>
                            <td>
                                <a href="{{ product.get_absolute_url }}">
                                    <img src="{{ product.image.url }}">
                                </a>
                            </td>
                            <td class="titillium-web-black">{{ product.name }}</td>
                            <td class="titillium-web-black">{{ item.quantity }}</td>
                            <td class="titillium-web-black"><a href="{% url 'cart:cart_remove' product.id %}">Убрать</a></td>
                            <td class="titillium-web-black">{{ item.price }} ₽</td>
                            <td class="titillium-web-black">{{ item.total_price }} ₽</td>
                        </tr>
                    {% endwith %}
                {% endfor %}
                <tr class="total">
                    <td class="titillium-web-bold" colspan="5">В сумме к оплате:</td>
                    <td class="titillium-web-bold">{{ cart.get_total_price }} ₽</td>
                </tr>
            </tbody>
        </table>
    </div>
{% endblock %}