myshop/about_us/urls.py
from . import views
from django.urls import re_path 


urlpatterns = [
    re_path('', views.about, name='about'),
]

myshop/cart/urls.py
from django.urls import re_path 
from . import views


urlpatterns = [
    re_path(r'^$', views.cart_detail, name='cart_detail'),
    re_path(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    re_path(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

myshop/myshop/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import include
from django.urls import re_path 

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'about_us/', include(('about_us.urls', 'about_us'), namespace='about_us')),
    re_path(r'^orders/', include(('orders.urls', 'orders'), namespace='orders')),
    re_path(r'^cart/', include(('cart.urls', "cart"), namespace='cart')),
    re_path(r'^', include(('shop.urls', 'shop'), namespace='shop')), 
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myshop/shop/urls.py
from django.urls import re_path 
from . import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    re_path(r'search/', views.search, name='search_results'),
    re_path(r'^$', views.product_list, name='product_list'),
    re_path(r'^(?P<category_slug>[-\w]+)/$',
        views.product_list,
        name='product_list_by_category'),
    re_path(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$',
        views.product_detail,
        name='product_detail'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myshop/about_us/models.py
from django.db import models

# Create your models here.

myshop/shop/models.py
from django.db import models
from django.urls import reverse

class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('shop:product_list_by_category',
                        args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', null=True, on_delete=models.SET_NULL)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    # image2 = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    # image3 = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    # image4 = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('shop:product_detail',
                        args=[self.id, self.slug])

myshop/about_us/views.py
from django.shortcuts import render

def about(request):
    return render(request, 'shop/about_us.html')

myshop/shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from cart.forms import CartAddProductForm
from django.db.models import Q # новый
from django.views.generic import TemplateView, ListView


def product_detail(request, id, slug):
    product = get_object_or_404(Product,
                                id=id,
                                slug=slug,
                                available=True)
    cart_product_form = CartAddProductForm()
    return render(request, 'shop/product/detail.html', {'product': product,
                                                        'cart_product_form': cart_product_form})

def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.all()
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request,
                  'shop/product/list.html',
                  {'category': category,
                   'categories': categories,
                   'products': products,
                   })

 
def search(request): 
    query = request.GET.get('q')
    object_list = Product.objects.filter(
        Q(name__icontains=query) | Q(description__icontains=query) | Q(name=query)
    )
    return render(request,
                'shop/search_results.html',
                {
                    'products': object_list,
                    'counter': len(object_list)
                })



# def cart_detail(request):
#     cart = Cart(request)
#     return render(request, 'cart/detail.html', {'cart': cart})

myshop/templates/shop/about_us.html
{% extends "shop/base.html" %}
{% load static %}
{% block content %}
    <center>
        <div>
                <img src="{% static 'img/image.jpg' %}" style="border-radius: 10%; margin-top: 195px;">
                <div class="titillium-web-semibold" style="font-size: 30px; margin-top: 20px">О нас</div>
        </div>
        <div style="font-family: 'Tilda Sans', sans-serif; font-size: 25px;">IBUY - сервис, который занимается доставкой вещей из Китая, Южной Кореи, Европы, а также может пополнить гардероб вещами из наличия.</div>
        <div class="titillium-web-semibold" style="font-size: 30px; margin-top: 20px">Отзывы</div>
        <div style="font-family: 'Tilda Sans', sans-serif; font-size: 25px;">Более 100 положительных отзывов по всему интернету - наше главное достижение и доказательство доверия клиентов.</div>
        <div class="titillium-web-semibold" style="font-size: 30px; margin-top: 20px">Аутентификация</div>
        <div style="font-family: 'Tilda Sans', sans-serif; font-size: 25px;">Каждый вложенный товар проходит проверку на подлинность.</div>
        <div class="titillium-web-semibold" style="font-size: 30px; margin-top: 20px">Доставка</div>
        <div style="font-family: 'Tilda Sans', sans-serif; font-size: 25px;">Заказы, оплаченные до 18:00(МСК), отправляем в тот же день. Доступны все популярные службы доставки.</div>
        <div class="titillium-web-semibold" style="font-size: 30px; margin-top: 20px">Оплата</div>
        <div style="font-family: 'Tilda Sans', sans-serif; font-size: 25px;">Принимаем в ряблях, долларах, юанях (Русские карты, крипто-кошельки, Alipay).</div>
        <div class="titillium-web-semibold" style="font-size: 30px; margin-top: 20px">Возврат</div>
        <div style="font-family: 'Tilda Sans', sans-serif; font-size: 25px;">Возврата  нет. Только в случае если вещь оказалась неоригинальной (такого нет и не было, каждая вещь проходит проверку на оригинальность перед публикацией).</div>
        <div class="titillium-web-semibold" style="font-size: 30px; margin-top: 20px">Дополнительно</div>
        <ul style="text-align: center; list-style-position: inside">
            <li style="font-family: 'Tilda Sans', sans-serif; font-size: 25px;">Доступна доставка курьером по Москве и Набережным Челнам.</li>
            <li style=" font-family: 'Tilda Sans', sans-serif; font-size: 25px;">При покупке двух и более товаров доставка бесплатная.</li>
            <li style=" font-family: 'Tilda Sans', sans-serif; font-size: 25px;">Рассматриваем обмены (имформацию уточняйте у <a href="https://t.me/IBUYrussia">менеджера</a>)</li>
        </ul>
    </center>
    <br>
{% endblock %}

myshop/templates/shop/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>{% block title %}My shop{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css'%}"> 
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Titillium+Web:ital,wght@0,200;0,300;0,400;0,600;0,700;0,900;1,200;1,300;1,400;1,600;1,700&display=swap" rel="stylesheet">
    <style>
            a.white_txt { 
                color: black;
            }
            a.white_txt:hover { 
                color:white;
            }
        </style>
    <script>
      function submitForm() {
        document.getElementById("search").submit();
      }
    </script>
</head>
<body>
    <nav>
        <div class="navbar">
          
            {% with total_items=cart|length %}
                <a href="{% url 'cart:cart_detail' %}">
                    <img src="{% static 'img/basket.svg' %}" class="basket" height="50px" width="100px" style="position: absolute; top: 32%; left: 7%;" />
                </a>
                <a href="{% url 'about_us:about' %}" style="font-family: 'Tilda Sans', sans-serif; position: absolute; top: 39%; left: 18%; color: black; font-size: 25px; text-decoration: none;">Инфо</a>
                <a href="{% url 'shop:product_list' %}" style="font-family: 'Tilda Sans', sans-serif; position: absolute; top: 39%; left: 28%; color: black; font-size: 25px; text-decoration: none;">Каталог </a>
                 <a href="https://t.me/IBUYrussia" target="_blank" title="Написать в Telegram" rel="noopener noreferrer"><div class="telegram-button"><i class="fa fa-telegram"></i></div></a>
            {% endwith %}
            <center> 
                <img src="{% static 'img/logo.png' %}" width="170" height="170">
            </center> 
              <!-- <form id="search" action="{% url 'shop:search_results' %}" method="get">
                <input name="q" type="text" placeholder="Search..."> 
                <i aria-hidden="true"></i>
              </form>-->
              <form id="search" method="get" action="{% url 'shop:search_results' %}">
                <div class="search-box" style="position: absolute; left: 78.5%; top: 30%;">
                    <input type="text" name="q" class="search-txt" placeholder="Найти товар"/>
                    <a class="search-btn" onclick=submitForm()>
                    <i class="fa fa-search" aria-hidden="true"></i>
                    </a>
                </div>
                </form>
        </div>
    </nav>
    <div>
        <br>
        {% block content %}
        {% endblock %}
    </div>
</body> 
</html>

myshop/templates/shop/search_results.html
{% extends "shop/base.html" %}
{% load static %}
{% block content %}
  <center>
    <div class="titillium-web-semibold" style="font-size: 30px; margin-top: 195px; margin-bottom: 50px;">Результаты поиска</div>
  </center>
   <center><div id="main" class="product-list" style="margin-left: auto; margin-right: auto;">
        <div class="product-grid">
          {%if counter != 0 %}
              {% for product in products %}
              <div class="item" style="padding-bottom: 40px;">

                  {% if product.available == True %}
                  <a href="{{ product.get_absolute_url }}" class="product-link">
                      <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}" 
                          alt="{{ product.name }}" 
                          class="product-image"
                          width="70%" height="70%">
                  </a>
                  <div class="text-center">
                  
                      <a href="{% url 'shop:product_list' %}{{ product.get_absolute_url }}" class="product-title">
                          {{ product.name }}
                      </a>
                      <div class="product-price">
                          {{ product.price }} ₽
                      </div>
                  </div>
                  {% else %}
                  <div class="image-container">
                      <a>
                          <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}" 
                              alt="{{ product.name }}" 
                              class="product-image"
                              width="70%" height="70%">
                          <div class="sold-out-tag">Распроданный</div>
                      </a>
                      <div class="product-details text-center">
                          <a class="product-title">{{ product.name }}</a>
                          <div class="product-price">{{ product.price }} ₽</div>
                      </div>
                  </div>
                  {% endif %}
                </div>
            {% endfor %}
          {% else %}
              <!-- <div class="titillium-web-semibold" style="font-size: 20px; margin-top: 30px; text-align: center;">Результаты поиска</div> -->
          {% endif %}
        </div>
    </div></center>
{% endblock %}